Feature/ Implement AWS KMS Signer
Signo-App/uma-protocol pull request #22
Opened 2023-05-09 20:17 UTC by RojhatToptamus

2023-05-10 08:11 UTC, KohliSuraj commented
> Uses KMS to sign transactions. [Example TX ](https://goerli.etherscan.io/tx/0x9243b48de981260d551811d9348688d2750bfc069a1f17c701518180d02284b9) TODO: Some transactions fail due to incorrect gas limits and prices specified in the TX Object. To fix that EIP1559 standard should be used.

From an implementation perspective, this is what I figured out:
- we've changed interface of `runTransaction` function to include  **contractAddress**.
- changed `type AugmentedSendOptions` i.e. `transactionConfig` to include **to** address
- `kms-signer` file, responsible for signing via KMS

2023-05-12 12:29 UTC, KohliSuraj requested changes

2023-05-12 12:29 UTC, KohliSuraj commented on packages/common/src/kms-signer.ts
> +    gasLimit: '0x11170',
@RojhatToptamus You mentioned in the description, that we might have to implement EIP 1559. I believe this code already implements it.

Why do we hardcode the gas price and gas limit here? I think transactions might be failing because of this

2023-05-12 12:29 UTC, KohliSuraj commented on packages/common/src/TransactionUtils.ts
> +    wrapperTxnConfig.type = "0x2";
@KohliSuraj this is incorrect need to refactor

2023-05-12 12:29 UTC, KohliSuraj commented on packages/common/src/aws-kms-signer.ts
> +    type: transactionConfig.gasPrice ? 1 : 2,
@KohliSuraj this type is not needed here, it's coming from calling function

2023-05-15 17:15 UTC, KohliSuraj commented on packages/common/src/aws-kms-signer.ts
> +    type: Number(transactionConfig.type),
isn't this incorrect

how will Number be applied to **type: process.env.KMS_SIGNER ? "0x2" : "0x0"**

2023-05-15 17:15 UTC, KohliSuraj commented on packages/common/src/TransactionUtils.ts
> +  const wrapperTxnConfig: AugmentedSendOptions = {
nice one. Much more cleaner 👍

2023-05-17 08:24 UTC, RojhatToptamus commented
We have modified our strategy. So to enhance the clarity we'll move forward with this PR #24 .

2023-05-17 08:25 UTC, closed without merging